# Generated by Django 4.2.16 on 2024-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripease1', '0002_alter_trip_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
